cfex_params:
- name: b
  min: 0.0
  max: 15
  init: 4.05
- name: satdk
  min: 0.0
  max: 0.00726
  init: 0.000338
  scale: log10
- name: satpsi
  min: 0.0
  max: 0.995
  init: 0.355
- name: maxsmc
  min: 0.16
  max: 0.6
  init: 0.439
- name: max_gw_storage
  min: 0.01
  max: 0.25
  init: 0.05
- name: Cgw
  min: 1.8e-06
  max: 0.0018
  init: 0.00018
  scale: log10
- name: expon
  min: 1.0
  max: 8.0
  init: 5.0
- name: Kn
  min: 0.0
  max: 1.0
  init: 0.3
- name: Klf
  min: 0.0
  max: 1.0
  init: 0.1
- name: refkdt
  min: 0.001
  max: 8.0
  init: 3.0
- name: slope
  min: 0.0
  max: 1.0
  init: 0.01
- name: wltsmc
  min: 0.0
  max: 0.138
  init: 0.066
- name: alpha_fc
  min: 0.15
  max: 0.33
  init: 0.2
- name: a_Xinanjiang_inflection_point_parameter
  min: -0.493
  max: 0.493
  init: 0.25
- name: b_Xinanjiang_shape_parameter
  min: 0.0009
  max: 10.0
  init: 2.5
- name: x_Xinanjiang_shape_parameter
  min: 0.0005
  max: 10.0
  init: 2.5
