casam_params:
- name: spf_factor
  min: 0.01
  max: 0.99
  init: 0.66
- name: frac_to_CR
  min: 0.01
  max: 0.99
  init: 0.44
- name: a
  min: -8.0
  max: -1.0
  init: -4.0
- name: b
  min: 0.5
  max: 5.0
  init: 2.0
- name: smcmax_1
  min: 0.2
  max: 0.7
  init: 0.45
- name: van_genuchten_alpha_1
  min: -5.0
  max: -1.0
  init: -3.0
- name: hydraulic_conductivity_1
  min: -4.0
  max: 2.0
  init: 0.0
- name: van_genuchten_n_1
  min: 1.01
  max: 4.0
  init: 1.5
- name: field_capacity
  min: 100.0
  max: 500.0
  init: 340.0
