sacsma_params:
- name: adimp
  min: 0.0
  max: 0.2
  init: 0.1
- name: lzfpm
  min: 40
  max: 600
  init: 320
- name: lzfsm
  min: 15
  max: 300
  init: 157.5
- name: lzpk
  min: 0.001
  max: 0.015
  init: 0.008
- name: lzsk
  min: 0.03
  max: 0.2
  init: 0.115
- name: lztwm
  min: 75
  max: 300
  init: 187.5
- name: pctim
  min: 0
  max: 0.05
  init: 0.05
- name: pfree
  min: 0
  max: 0.5
  init: 0.25
- name: rexp
  min: 1.4
  max: 3.5
  init: 2.45
- name: riva
  min: 0
  max: 0.2
  init: 0
- name: uzfwm
  min: 10
  max: 75
  init: 42.5
- name: uzk
  min: 0.2
  max: 0.5
  init: 0.3
- name: uztwm
  min: 25
  max: 125
  init: 75
- name: zperc
  min: 20
  max: 300
  init: 160
