snow17_params:
- name: scf
  min: 0.7
  max: 1.7
  init: 1.15
- name: mfmax
  min: 0.5
  max: 2.2
  init: 1.35
- name: mfmin
  min: 0.1
  max: 0.6
  init: 0.35
- name: uadj
  min: 0.05
  max: 0.2
  init: 0.125
- name: si
  min: 1
  max: 9999
  init: 999
- name: adc2
  min: 0.11
  max: 0.3
  init: 0.243
- name: adc3
  min: 0.2
  max: 0.52
  init: 0.423
- name: adc4
  min: 0.45
  max: 0.65
  init: 0.578
- name: adc5
  min: 0.5
  max: 0.77
  init: 0.688
- name: adc6
  min: 0.56
  max: 0.81
  init: 0.734
- name: adc7
  min: 0.61
  max: 0.86
  init: 0.785
- name: adc8
  min: 0.65
  max: 0.89
  init: 0.819
- name: adc9
  min: 0.69
  max: 0.93
  init: 0.859
- name: adc10
  min: 0.82
  max: 0.96
  init: 0.919
