topmodel_params:
- name: szm
  init: 0.032
  min: 0.001
  max: 0.2
- name: sr0
  init: 0.002
  min: 0.001
  max: 0.04
- name: srmax
  init: 0.05
  min: 0.001
  max: 1
- name: td
  init: 50
  min: 0.001
  max: 100
- name: t0
  init: 5
  min: -8
  max: 8
- name: chv
  init: 3600
  min: 100
  max: 4000
- name: rv
  init: 1000
  min: 10
  max: 4000
