general:
  strategy:
    type: estimation
    algorithm: dds #pso
    parameters:
      particles: 20
      pool: 2
      options:
        c1: 1.5
        c2: 2.0
        w: 0.9
      options_schedule:
        type: linear
        end:
          c1: 0.5
          c2: 0.5
          w: 0.4
      initialization:
        nearby_fraction: 0.5
        noise_fraction: 0.2
  log: true
  start_iteration: 0
  iterations: 500 #50
  random_seed: 444
  workdir: ./
calibration:
  params_dir: calibration
model:
  type: ngen
  binary: <*>
  realization: <*>
  hydrofabric: <*>
  eval_feature: <*>
  strategy: uniform
  params: <*>
  eval_params:
    objective: kling_gupta
    target: min
  plugins:
  - ngen_cal_plugins.save_divide_output_plugin.SaveData
  - ngen_cal_plugins.save_sim_obs_plugin.SaveData
  - ngen_cal_plugins.metrics.ComputeMetrics
