general:
  strategy:
    type: estimation
    algorithm: dds #pso
    parameters:
      particles: 16
      pool: 4
      options:
        c1: 1.2
        c2: 1.2
        w: 0.9
      options_schedule:
        type: linear
        end:
          c1: 0.5
          c2: 1.8
          w: 0.3
      initialization:
        #best_path: "path/to/pso_global_best/"
        nearby_fraction: 0.1
        noise_fraction: 0.2
      particle_reset:
        enabled: true
        patience: 4
        reset_fraction: 1.0
        preserve_global_best: true
  log: true
  start_iteration: 0
  iterations: 300
  random_seed: 444
  workdir: ./
calibration:
  params_dir: calibration
model:
  type: ngen
  binary: <*>
  realization: <*>
  hydrofabric: <*>
  eval_feature: <*>
  strategy: uniform
  params: <*>
  eval_params:
    objective: kling_gupta
    target: min
  plugins:
  - ngen_cal_plugins.save_divide_output_plugin.SaveData
  - ngen_cal_plugins.save_sim_obs_plugin.SaveData
  - ngen_cal_plugins.metrics.ComputeMetrics
