formulations:
  pet_cfe_s:
    models: "PET, CFE, T-route"
    model_instances:
      CFE:
        - name: cfe-s
          basefile: "config_cfe-s.yaml"
          repo_name: "cfe"
          calib_params_block: "cfes_params"

  pet_cfe_x:
    models: "PET, CFE, T-route"
    model_instances:
      CFE:
        - name: cfe-x
          basefile: "config_cfe-x.yaml"
          repo_name: "cfe"
          calib_params_block: "cfex_params"

  pet_topmodel:
    models: "PET, TopModel, T-route"

  nom_cfe_s:
    models: "NOM, CFE, T-route"
    model_instances:
      CFE:
        - name: cfe-s
          basefile: "config_cfe-s.yaml"
          repo_name: "cfe"
          calib_params_block: "cfes_params"

  nom_cfe_x:
    models: "NOM, CFE, T-route"
    model_instances:
      CFE:
        - name: cfe-x
          basefile: "config_cfe-x.yaml"
          repo_name: "cfe"
          calib_params_block: "cfex_params"

groups:
  formulations_1:
    - pet_cfe_s
    - pet_cfe_x
    - pet_topmodel

  formulations_2:
    - nom_cfe_s
    - nom_cfe_x

mapping:
  "02299950":
    - formulations_1
    - formulations_2

  "08070500":
    - formulations_1
    - formulations_2

  "03574500":
    - formulations_1
    - formulations_2

  "04231000":
    - formulations_2

  "03366500":
    - formulations_2

  "04282000":
    - formulations_2

  "05061000":
    - formulations_2

  "09504420":
    - formulations_2

  "11264500":
    - formulations_2
